title: "mf://TODO"
subtitle: "Michael Forrest's Museum of Unfinished Projects"
pygments: true
exclude: ['designs']
stylus:
  compress: true
  path: /usr/local/share/npm/bin/stylus
excerpt_separator: "\n\n\n\n"